services:
  # Main web application container
  web-app:
    build:
      context: .
      dockerfile: Dockerfile-web      
    image: support-hub:v3
    restart: unless-stopped # restart unless containers are stopped manually
    container_name: supporthub
    ports:
      - "80:80" # map host port 80 to container port 80
    volumes:
      # Persistent storage for uploaded ticket images
      - .:/var/www/html
      - stored_images:/var/lib/tickets/data
       # Secret files for database credentials
      - ./secrets/db_pass:/run/secrets/db_pass:ro
      - ./secrets/db_host:/run/secrets/db_host:ro
      - ./secrets/db_name:/run/secrets/db_name:ro
      - ./secrets/db_user:/run/secrets/db_user:ro
      - ./secrets/calendar.json:/run/secrets/calendar.json:ro


  # Email/cron service container 
  email-app:
    build:
      context: .
      dockerfile: Dockerfile-cron
    image: support-hub-email-service:v3
    restart: unless-stopped
    container_name: supporthubemailservice
    volumes:
       # Secret files for database credentials
      - ./secrets/db_pass:/run/secrets/db_pass:ro
      - ./secrets/db_host:/run/secrets/db_host:ro
      - ./secrets/db_name:/run/secrets/db_name:ro
      - ./secrets/db_user:/run/secrets/db_user:ro
      - ./secrets/mail_host:/run/secrets/mail_host:ro
      - ./secrets/mail_port:/run/secrets/mail_port:ro     




# Named volumes for persistent storage
volumes:
  stored_images: # store uploaded ticket images
  